:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid

:queues:
    - default
:limits:
  default: 20
:schedule:
  rank_score_job:
    every: '4h'
    class: Schedules::RankScoreJob
    description: 'Rank Score'
development:
  :concurrency: 5
staging:
  :concurrency: 5
production:
  :concurrency: 20
